# Auto-generated by Terraform after `terraform apply`.
# DO NOT EDIT MANUALLY — changes will be overwritten on the next apply.
# IPs come from libvirt's DHCP lease for each VM.

all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ${ansible_ssh_key}
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

  children:
    db:
      hosts:
        db-vm:
          ansible_host: ${db_ip}

    workers:
      hosts:
        worker-vm:
          ansible_host: ${worker_ip}
